-- CreateEnum
CREATE TYPE "TYPE" AS ENUM ('PRIVATE', 'PUBLIC');

-- AlterTable
ALTER TABLE "Subject" ADD COLUMN     "timer" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN     "type" "TYPE" NOT NULL DEFAULT 'PUBLIC';
